name: 'fmtok8s-ci'
description: From Monolith to K8S Continuous Integration Action
inputs:
  default_branch:
    description: 'Default branch'
    required: false
    default: 'main'
  github_token:
    description: 'Github token'
    required: true
outputs:
  execute_helm_publish:
    description: |
      Shows if you can publish Helm charts. (boolean)
  version_to_use:
    description: |
      Is a correct semver value to uso on release process. (string)
  execute_docker_publish:
    description: |
      Shows if you can execute docker build/publish process. (boolean)
  execute_native_publish:
    description: |
      Shows if you can execute native build/publish process.
runs:
  using: 'node16'
  main: 'dist/index.js'