name: 'fmtok8s-ci'
description: From Monolith to K8S Continuous Integration Action
inputs:
  default-branch:
    description: 'Default branch'
    required: false
    default: 'main'
  github_token:
    description: 'Github token'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'